name: guitartuner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_gauges: ^31.1.19
  flutter_audio_capture: ^1.1.11        
  pitch_detector_dart: ^0.0.7 
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/audio/tick.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appiconguitar.png"
  remove_alpha_ios: true   # Required by Apple if your icon has transparency

